//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated with cs-generation.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

export interface InterfaceChild {
   id: number;
}
