//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated with cs-generation.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import { InterfaceChild } from './interface-child';

export interface InterfaceRoot {
   id: number;
   name: string;
   createdTime: string;
   nonAnnotatedChild: any;
   annotatedChild: InterfaceChild;
   childIds: number[];
   unknownChildren: any[];
   children: InterfaceChild[];
   builtInDict: { [key: number]: string };
   customDict: { [key: number]: InterfaceChild };
   customListInDict: { [key: number]: InterfaceChild[] };
   crazyComplexType: { [key: number]: { [key: number]: InterfaceChild[] } };
}
